name: Azure VM Deployment

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.1
      with:
        ssh-private-key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
    
    - name: Install Apache and PHP
      run: |
        sudo apt-get update
        sudo apt-get install -y apache2 php libapache2-mod-php
        sudo systemctl start apache2
        sudo systemctl enable apache2
    
    - name: Copy files to Azure VM
      run: |
        scp -o StrictHostKeyChecking=no -r PHPMailer login.html otp.php status.php ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_PUBLIC_IP }}:/var/www/html
    
    - name: Notify deployment success
      run: echo "Deployment to Azure VM complete."

    - name: Print Public IP URL
      run: echo "Access your web app at http://${{ secrets.AZURE_VM_PUBLIC_IP }}"
